[package]
name = "day20"
version = "0.1.0"
authors = ["Noble-Mushtak <noblemushtak.public@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multimap = "0.8.2"
peg = "0.6.3"
