[package]
name = "day21"
version = "0.1.0"
authors = ["Noble-Mushtak <noblemushtak.public@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
peg = "0.6.3"
